serverless/examples

aws-node-scheduled-cron/README.md
aws-node-scheduled-cron/handler.js
aws-node-scheduled-cron/serverless.yml

Going to move over the examples from `serverless/serverless/docs` to this repo.
I'm working on a way to pull these into the site

Move cron example from docs to examples

---

community-examples.json

Adding a tutorial/sample project I created.  This collects custom metric data from an RDS server in a VPC and push those custom metrics into cloudwatch metrics.  This was done to work with a bare-bones environment without a NAT Gateway using chained Lambdas.

Adding a CloudWatch RDS Custom Metric gatherer

---

aws-node-iot-event/README.md
aws-node-iot-event/handler.js
aws-node-iot-event/package.json
aws-node-iot-event/serverless.yml

add iot example

---

aws-node-function-compiled-with-babel/package.json

I was getting an error after installing the dependencies from NPM and running `serverless deploy`:
```
$ sls deploy -v
Serverless: Packaging service...
/Users/cmoel/Desktop/sls-babel/node_modules/serverless-babel-plugin/index.js:56
const stdout = result.stdout.toString();
^
TypeError: Cannot read property 'toString' of null
```
(Full stacktrace: https://gist.github.com/cmoel/3707297a818f4eb79b186ac4e120e419.)
I found this was related to not having the `babel` executable available in `node_modules/.bin/` ( https://github.com/serverless/serverless-babel-plugin/blob/master/index.js#L55). Installing `babel-cli` fixed this issue for me.

Add babel-cli dependency to Babel example

---

aws-node-single-page-app-via-cloudfront/serverless-single-page-app-plugin/index.js

At line 63 in the single page app plugin, there was an extra comma that was resulting in an error when running serverless operations.

Remove extra comma in provider request

---

aws-node-rest-api-with-dynamodb/todos/update.js

put is not the best option to explain DynamoDB Item update. In the earlier example, the attributes that are not updated, like createdAt will be lost, as put writes the entire new document (and the current example does not include the createdAt attribute), resulting in the attributes not supplied in the put being lost. Also updated the validation condition from AND (&&) to OR (||)

change from put to update

---

aws-node-rest-api-with-dynamodb/todos/update.js

improve rest example

---

aws-node-rest-api-with-dynamodb/serverless.yml
aws-node-rest-api-with-dynamodb/todos/create.js
aws-node-rest-api-with-dynamodb/todos/delete.js
aws-node-rest-api-with-dynamodb/todos/get.js
aws-node-rest-api-with-dynamodb/todos/list.js
aws-node-rest-api-with-dynamodb/todos/update.js

Issue Ref: #49
---
This is simply to ensure that anyone copying and pasting this example won't accidentally open up access to every DynamoDB table of theirs in the us-east-1 region.
Assuming the following:
- Service Name: `serverless-rest-api-with-dynamodb`
- Region: `us-east-1`
- Stage: `dev`
This will create a DynamoDB resource with a table name of:
`serverless-rest-api-with-dynamodb-dev`
And provide access to an ARN of:
`arn:aws:dynamodb:us-east-1:*:table/serverless-rest-api-with-dynamodb-dev`

Lock down permissions to a specific table

---

aws-node-rest-api-with-dynamodb/serverless.yml

Deploying the example fails as described in #70. Setting a custom table
name by setting DYNAMODB_TABLE in the environment will sucessfully
deploy, but the deployed code will fail at runtime, since it references
the wrong table name.
This fixes it by referencing the generated table name under
provider.environment.
fixes #70

fix environment reference to DYNAMODB_TABLE

---

aws-node-fetch-file-and-store-in-s3/handler.js
aws-node-fetch-file-and-store-in-s3/package.json
aws-node-rest-api-with-dynamodb/package.json
aws-node-rest-api-with-dynamodb/todos/create.js
aws-node-rest-api-with-dynamodb/todos/delete.js
aws-node-rest-api-with-dynamodb/todos/get.js
aws-node-rest-api-with-dynamodb/todos/list.js
aws-node-rest-api-with-dynamodb/todos/update.js
aws-node-text-analysis-via-sns-post-processing/addNote.js
aws-node-text-analysis-via-sns-post-processing/package.json

aws-sdk is automatically included in the lambda context. Adding it is
unnecessary, and increases the size of the service .zip file by 2
magnitudes.

remove aws-sdk from dependencies

---

aws-node-auth0-custom-authorizers-api/handler.js

Hey! This is a pull-request to solve an authorization issue caused by a change made by Auth0 to the `jsonwebtoken` package since december 2016.
@michieldewilde has opened an issue (Verify JWT Auth0 #62) about this - which confirms someone else is also experiencing the same problem.
Reference: https://auth0.com/forum/t/client-secret-stored-without-base64-encoding/4338/8

Passing auth0 client secret as string without base64 encoding #62

---

README.md
aws-node-rest-api-offline/.gitignore
aws-node-rest-api-offline/README.md
aws-node-rest-api-offline/offline/migrations/todos.json
aws-node-rest-api-offline/package.json
aws-node-rest-api-offline/serverless.yml
aws-node-rest-api-offline/todos/create.js
aws-node-rest-api-offline/todos/delete.js
aws-node-rest-api-offline/todos/dynamodb.js
aws-node-rest-api-offline/todos/get.js
aws-node-rest-api-offline/todos/list.js
aws-node-rest-api-offline/todos/update.js

This adds an example identical to aws-node-rest-api-with-dynamodb, but
with the ability to run it offline using the plugins serverless-offline
and serverless-dynamodb-local.
fixes #14

add offline example

---

README.md
azure-node-simple-http-endpoint/.gitignore
azure-node-simple-http-endpoint/README.md
azure-node-simple-http-endpoint/handler.js
azure-node-simple-http-endpoint/package.json
azure-node-simple-http-endpoint/serverless.yml

Adds 1 example for Azure node http
Confirmed I ran eslint

Added azure-node-http example :tada:

---

aws-node-fetch-file-and-store-in-s3/serverless.yml

Only allow to create objects in specific bucket.
part of #49

aws-node-fetch-file-and-store-in-s3: lock down permissions

---

README.md
community-examples.json

Hi.
I made the boilerplate example about [Isomorphic rendering ReactJS in Serverless].
It's still in progress, but I think some people can get help from this example.
Thanks.

Added Serverless ReactJS Universal Rendering Boilerplate 

---

google-node-simple-http-endpoint/serverless.yml

This is necessary since Google will use this file to download all the dependencies in the Cloud.

Remove package.json from excludes in Google example

---

aws-node-rest-api-with-dynamodb-and-offline/serverless.yml

I was getting connection errors when running the dynamodb offline example.
It seems related to [a typo in their readme that was corrected recently](https://github.com/99xt/serverless-dynamodb-local/commit/19b6991675bf98acd426370bccd8e155c4cdd2b8).
Once I made that change, the offline example was working

Fix type: migration should be migrate

---

README.md
generate-readme.js
openwhisk-php-simple/.gitignore
openwhisk-php-simple/README.md
openwhisk-php-simple/handler.php
openwhisk-php-simple/package.json
openwhisk-php-simple/serverless.yml

PHP support have been added to OpenWhisk provider plugin:
https://github.com/serverless/serverless-openwhisk/releases/tag/v0.9.0
I've added an example for this and fixed `generate-readme.js` to support PHP runtime.
@pmuens can you have a quick look over this before I merge?

Adding PHP example for OpenWhisk.

---

aws-node-github-webhook-listener/handler.js
aws-node-rekognition-analysis-s3-image/handler.js
aws-node-rest-api-mongodb/handler.js
aws-node-rest-api-with-dynamodb-and-offline/todos/create.js
aws-node-rest-api-with-dynamodb-and-offline/todos/delete.js
aws-node-rest-api-with-dynamodb-and-offline/todos/get.js
aws-node-rest-api-with-dynamodb-and-offline/todos/list.js
aws-node-rest-api-with-dynamodb-and-offline/todos/update.js
aws-node-rest-api-with-dynamodb/todos/create.js
aws-node-rest-api-with-dynamodb/todos/delete.js
aws-node-rest-api-with-dynamodb/todos/get.js
aws-node-rest-api-with-dynamodb/todos/list.js
aws-node-rest-api-with-dynamodb/todos/update.js
aws-node-stripe-integration/handler.js
aws-node-text-analysis-via-sns-post-processing/addNote.js
package-lock.json

As earlier discussed in issue #186, I took the liberty of (hopefully) updating all `aws-node-...` examples with lamdas that responds to API Gateway-events and changed their error responses so that they respond correctly.
I also want to point out that I haven't changed the structure of the code or anything. I have only changed the original callbacks, e.g.:
```js
if (error) {
callback(new Error('Something went wrong'));
}
```
I have transformed them so that the lambdas ”don't think” that an error occured, e.g.:
```js
if (error) {
callback(null, {
statusCode: error.statusCode || 501,
headers: { 'Content-Type': 'plain/text' },
body: error.message || 'Internal server error',
});
}
```
In the first case an http request would always return a `502 Bad Gateway` response. But in the latter case the …

Fix API Gateway error responses

---

aws-node-rest-api-mongodb/README.md

hey! super awesome examples, small improvement to make trying it out easier
when I show it off to people
* city violates the value constraint causing the example to
fail when copy+pasted, should not have a space to make setup
as easy as possible (https://github.com/chriso/validator.js/)

readme should have valid examples

---

README.md
aws-node-auth0-cognito-custom-authorizers-api/.gitignore
aws-node-auth0-cognito-custom-authorizers-api/README.md
aws-node-auth0-cognito-custom-authorizers-api/auth.js
aws-node-auth0-cognito-custom-authorizers-api/handler.js
aws-node-auth0-cognito-custom-authorizers-api/package.json
aws-node-auth0-cognito-custom-authorizers-api/serverless.yml

Fixes issue #200 by adding a new authenticator node.js example which works with [JWKS](https://auth0.com/docs/jwks) tokens.
This authenticator can be used either with Auth0 or AWS Cognito (tutorial in README.md).

Add JWKS token authentication (for Auth0 and AWS Cognito)

---

README.md
aws-node-dynamodb-backup/README.md
aws-node-dynamodb-backup/handler.js
aws-node-dynamodb-backup/package.json
aws-node-dynamodb-backup/serverless.yml

I use this at work to have a backup of our DynamoDB tables. It also serves as a handy fallback when the inevitable "dynamodb throughput exceeded" occurs.

Dynamodb streams to S3 (backup) example

---

aws-node-auth0-custom-authorizers-api/.gitignore
aws-node-auth0-custom-authorizers-api/README.md
aws-node-auth0-custom-authorizers-api/frontend/index.html
aws-node-auth0-custom-authorizers-api/handler.js
aws-node-auth0-custom-authorizers-api/package.json
aws-node-auth0-custom-authorizers-api/secrets.example.json
aws-node-auth0-custom-authorizers-api/serverless.yml

Trying to fix auth0 protected routes example

update jwt example auth backend

---

aws-python-rest-api-with-dynamodb/README.md

As the package.json file has no dependencies running the following will have no effect:
```npm install```
The correct command should be as follows:
```npm install -g serverless```

Fixing SETUP typo in README.md

---

community-examples.json

This example is to execute ssh command with OpenWhisk
https://github.com/upgle/serverless-openwhisk-ssh

Add Serverless SSH Command to community-examples.json

---

aws-node-rest-api-with-dynamodb/serverless.yml

Target example: 
aws-node-rest-api-with-dynamodb
After `deploy`, get error messages when create a new todo list:
$ curl -X POST ${url} --data '{ "text": "Learn Serverless" }'
{"message": "Internal server error"}
this PR is to fix above issue.

bugfix - [aws-node-rest-api-with-dynamodb] - Internal server error

---

aws-node-graphql-api-with-dynamodb/handler.js

Server error
```
);
^
SyntaxError: Unexpected token )
at Object.exports.runInThisContext (vm.js:76:16)
```

remove error comma

---

aws-node-rest-api-mongodb/handler.js
aws-node-rest-api-mongodb/model/User.js

This PR aims to fix the current `aws-node-rest-api-mongodb` example by using the newest declarations from mongoose, removing unused variables and lines, moving stuff to single line when possible and creating connections wrappers functions to avoid always re-declaring the `.finally(() => db.close())`.
Main change:
```
const dbExecute = (db, fn) => db.then(fn).finally(() => db.close());
function dbConnectAndExecute(dbUrl, fn) {
return dbExecute(mongoose.connect(dbUrl, { useMongoClient: true }), fn);
}
```

enhancement-fix/aws-node-rest-api-mongodb

---

aws-node-single-page-app-via-cloudfront/serverless-single-page-app-plugin/index.js

The flag deletes all the files that are in the bucket that are not in the `app` directory.
Useful to Single Page Applications that generate different files on each build (like React).

Add `--delete` argument to sync command

---

aws-node-auth0-custom-authorizers-api/README.md
aws-node-auth0-custom-authorizers-api/handler.js
aws-node-auth0-custom-authorizers-api/public_key-example
aws-node-auth0-custom-authorizers-api/secrets.example.json

512acb105359b75e0ddc1ae59c585d76d50c08f0 fixed the handler, but didn't include the nessecary `README.md` changes.

Update aws-node-auth0-custom-authorizers-api Readme to reflect code

---

aws-node-single-page-app-via-cloudfront/README.md
aws-node-single-page-app-via-cloudfront/serverless-single-page-app-plugin/index.js

Invalidating CloudFront's cache is required for s3 bucket changes to be reflected immediately.
Changes in this pr:
1. Add prerequisite to node >= 8 in readme (since I'm using `async/await` in the plugin).
2. Update readme with information about re-deploying.
3. Added the `invalidateCloudFrontCache` to the code (uses the `aws` cli).

Add invalidateCloudFrontCache command to serverless-single-page-app-plugin

---

aws-golang-simple-http-endpoint/hello/main.go
aws-golang-simple-http-endpoint/world/main.go

Updating golang example to leverage the AWS Lambda API Gateway Proxy Request struct by default (as this example expects the default behavior).

updating golang example to leverage events API

---

aws-node-auth0-custom-authorizers-api/handler.js

The line I just removed was called right after an async call, so it was always executed executing the `callback` function.
Then, when the async operation complete and its callback is called, the `callback` function was called again
```
doAsyncCall((err) => {
doThings...
callback();
});
callback();
```
This issue was reported in https://github.com/dherault/serverless-offline/issues/405#issuecomment-433698553

Fix auth0 example calling the callback twice

---

aws-node-vue-nuxt-ssr/readme.md

Fixes a rendering bug in the new serverless.com examples page.

Add metadata to aws-node-vue-nuxt-ssr readme.md

---

README.md
aws-python-simple-http-endpoint/serverless.yml
google-python-simple-http-endpoint/README.md
google-python-simple-http-endpoint/handler.py
google-python-simple-http-endpoint/main.py
google-python-simple-http-endpoint/package.json
google-python-simple-http-endpoint/serverless.yml

This example demonstrates how to setup a simple python HTTP GET endpoint within the GCF python3.7 runtime. When you fetch the endpoint we've set up here you'll see the time returned for the given request type.

GCF simple python http endpoint example

---

README.md
google-golang-simple-http-endpoint/.gcloudignore
google-golang-simple-http-endpoint/README.md
google-golang-simple-http-endpoint/hello.go
google-golang-simple-http-endpoint/package.json
google-golang-simple-http-endpoint/serverless.yml

The golang runtime in GCF is still in `alpha` but it slated for release to `beta` shortly. In the meantime let's get a few examples working with the serverless framework!
**NOTES**
- Your function must be exported (e.g `Hello`)
- You must define a non-main package, which can have an arbitrary name: `package p`
- Your function code may not contain `package main` or a `func main()`

adding GCF golang runtime example with simple http endpoint

---

README.md
community-examples.json

initial one had a few issues, including blocking ones (eg: runtime=node4) and the maintainer has not responded to a PR: https://github.com/ivanderbu2/serverless-newsletter-signup/pull/2

point newsletter example to updated fork

---

aws-golang-dynamo-stream-to-elasticsearch/README.md
aws-golang-dynamo-stream-to-elasticsearch/serverless.yml

disable AccessPolicies per default
Since the Lambda has access to ES anyway via lambda role, it's not necessary to have an open access set per default.

Fix/open access policy in aws-golang-dynamo-stream-to-elasticsearch

---

.eslintrc.json

This marks the main directory as the top-level for the project, stopping ESLint from looking in parent directories for more .eslintrc files.

eslint: Mark as root config

---

aws-python-simple-http-endpoint/serverless.yml

As of November 2019, [Python 3.7 is supported by AWS Lambda]. Let's update the comment from Python 3.6 to 3.7, as it is the [latest stable release](https://docs.python.org/3.7/) of the language.
If this change is approved, we might consider adding the same comment to Python `serverless.yml` files.

Python 3.7 support in comment

---

aws-python-rest-api-with-dynamodb/todos/create.py

`return` statement is not needed after an exception is raised.

Return is not needed after an exception is raised

---

aws-node-auth0-custom-authorizers-api/README.md
aws-node-auth0-custom-authorizers-api/serverless.yml

What's new?
- fixed typo in README
- NodeJS version `6.10` in serverless.yml is deprecated. I updated the serverless.yml file accordingly.

Fix typo + new NodeJS version

---

README.md
aws-node-puppeteer/serverless.yml

Is this correct? I get a warning from Serverless that the max timeout API Gateway and the Serverless config are not the same.
```
Serverless: WARNING: Function crawl has timeout of 60 seconds, however, it's attached to API Gateway so it's automatically limited to 30 seconds.
```

Update timeout to match API Gateway

---

aws-node-graphql-api-with-dynamodb/serverless.yml

Lambda no longer support Node 6.x - updated the serverless.yml with the latest supported runtime - 10.x

Update Node runtime to 10.x from 6.x (no longer supported)

---

aws-python-rest-api-with-pynamodb/requirements.txt

previous versions were using vendored "requests" from botocore, which is deprecated

fix: bump pynamodb to 4.3.1

---

aws-node-graphql-and-rds/serverless.yml

Node.js 8.10 has reached its end of life on Lambda, therefore this boilerplate no longer works. This PR bumps the environment to Node.js 12.x

Update Node.js runtime to 12.x

---

aws-python-rest-api-with-dynamodb/serverless.yml

This PR concerns the "aws-python-rest-api-with-dynamodb" example.
The commit `45bd5ee1a975735783565a6e48259f293d5e42cd` inserted a regression and generate the following error: "AttributeError: 'datetime.datetime' object has no attribute 'timestamp'".
Indeed, the example was written in python 2.7 but datetime.timestamp() is only available from python 3.3 and later.
I upgraded and tested it successfully in Python 3.8.

upgrade to python 3.8 to fix timestamp bug

---

aws-golang-http-get-post/serverless.yml

Changing the packaging to be individual instead of together. This has large efficiency gains in larger Go projects.

Make packaging more efficent

---

aws-python-pynamodb-s3-sigurl/README.md
aws-python-pynamodb-s3-sigurl/package-lock.json
aws-python-pynamodb-s3-sigurl/package.json

Fix aws python pynamodb s3 sigurl obsolete dependency (closes #364)

---

README.md
aws-python-rest-api-with-pymongo/README.md
aws-python-rest-api-with-pymongo/item/create.py
aws-python-rest-api-with-pymongo/item/delete.py
aws-python-rest-api-with-pymongo/item/get.py
aws-python-rest-api-with-pymongo/item/list.py
aws-python-rest-api-with-pymongo/package.json
aws-python-rest-api-with-pymongo/requirements.txt
aws-python-rest-api-with-pymongo/serverless.yml

Hello! Noticed there was not a python Pymongo example
Below is a new Aws Python Rest Api With Pymongo example.
Step-by-Step should be detailed in the README.md, please let me know if you have any questions!

New example: PyMongo

---

aws-node-scheduled-cron/serverless.yml

To fix error returned from AWS after `serverless deploy`
> The runtime parameter of nodejs8.10 is no longer supported for creating or updating AWS Lambda functions. We recommend you use the new runtime (nodejs12.x) while creating or updating functions

Update node runtime to 12.x

---

aws-node-single-page-app-via-cloudfront/serverless-single-page-app-plugin/index.js

Added region and profile support at `runAwsCommand`. User can specify `region` and/or `profile` at the provider section of serverless.yml.

Support region and profile

---

aws-node-auth0-custom-authorizers-api/serverless.yml

It seems to me that it makes little sense to specify `cors: true` outside of the HTTP Event configuration
Linter: not needed, just YAML changes.

chore: remove cors: true from the authorizer

---

aws-node-upload-to-s3-and-postprocess/README.md
aws-node-upload-to-s3-and-postprocess/frontend/index.template.html
aws-node-upload-to-s3-and-postprocess/generate-form.js
aws-node-upload-to-s3-and-postprocess/package.json

Updated aws-node-upload-to-s3-and-postprocess example to use signing key with AWS Signature Version 4 (AWS4-HMAC-SHA256)

Updated aws-node-upload-to-s3-and-postprocess with AWS4-HMAC-SHA256

---

README.md
community-examples.json

This project handles the use-case for labelling the image stored in s3. AWS Rekognition is used for getting the labels for the image and lambda functions stores the label and associated file details in DynamoDB. Another API endpoint is also provided to retrieve the images based on the labels.

Add community example for Serverless Image Labelling

---

aws-node-typescript-rest-api-with-dynamodb/todos/create.ts

The `result` variable doesn't contain any data for a DynamoDB Put op. So return `params.Item` instead, like in the non-TypeScript version.

return successfully saved data

---

README.md
community-examples.json

adding serverless http headers checks project

---

aws-node-typescript-rest-api-with-dynamodb/README.md
aws-node-typescript-rest-api-with-dynamodb/serverless.yml
aws-node-typescript-rest-api-with-dynamodb/todos/get.ts
aws-node-typescript-rest-api-with-dynamodb/todos/list.ts
aws-node-typescript-rest-api-with-dynamodb/todos/update.ts

Adding code for GET, LIST and PUT operations as well as updating readme.md

Adding GET, LIST, PUT operations to rest-api-typescript-dynamodb

---

aws-node-rest-api-typescript/serverless.template.yml
aws-node-rest-api/README.md
aws-node-rest-api/serverless.template.yml
aws-python-rest-api/README.md
aws-python-rest-api/serverless.template.yml

Update templates to use serverless.template.yml

Update templates to use serverless.template.yml

---

aws-python-rest-api-with-dynamodb/serverless.yml

The current version of Serverless Framework is 2.1.1 and the specified is 2.0.0.
Due to this it will raise you the following error: The Serverless version (2.1.1) does not satisfy the "frameworkVersion" (>=1.1.0 <2.0.0) in serverless.yml

update the version of Serverless Framework

---

aws-node-rest-api-with-dynamodb-and-offline/README.md
aws-node-rest-api-with-dynamodb-and-offline/dynamodb/Dockerfile
aws-node-rest-api-with-dynamodb-and-offline/dynamodb/docker-compose.yml
aws-node-rest-api-with-dynamodb-and-offline/package.json
aws-node-rest-api-with-dynamodb-and-offline/serverless.yml

[Serverless REST API with DynamoDB and offline support](https://github.com/serverless/examples/tree/master/aws-node-rest-api-with-dynamodb-and-offline): Adds optional persistent docker dynamodb setup for development and testing.

Serverless REST API with DynamoDB and offline support: optional persistent docker dynamodb setup

---

README.md
aws-node-sqs-worker/.gitignore
aws-node-sqs-worker/README.md
aws-node-sqs-worker/handler.js
aws-node-sqs-worker/package.json
aws-node-sqs-worker/serverless.template.yml
aws-node-sqs-worker/serverless.yml

Introduces a new `aws-node-sqs-worker` template

feat: Add `aws-node-sqs-worker` template

---

aws-python-flask-api/serverless.template.yml
aws-python-flask-dynamodb-api/serverless.template.yml

Adds missing `serverless.template.yml` files for Flask-based examples

fix: Add missing template for `aws-python-flask-api`

---

aws-node-sqs-worker/serverless.yml
aws-python-sqs-worker/serverless.yml

It turned out that `sls publish` does not support publishing templates with `!Ref` reference - it works fine with `Ref:` though, hence the following change.

fix: Use `Ref:` instead of `!Ref` in `sqs` templates

---

aws-node-scheduled-cron/handler.js

Since there is no callback and there function is not async the enterprise-plugin will not write a log to CloudWatch.

Add async to handler in order to end function

---

aws-python-flask-api/README.md

Without running pip install, I ran into the following error in CloudWatch.
```
Runtime.HandlerNotFound: Handler 'handler' missing on module 'wsgi_handler'
```

Update aws-python-flask-api README.md to include pip install

---

aws-node-rest-api/serverless.yml
aws-python-rest-api/serverless.yml

Remove `org` and `app` to not cause issues when using these templates with interactive flow

refactor: Remove `org` and `app` from selected templates

---

aws-ruby-line-bot/serverless.yml
aws-ruby-simple-http-endpoint/serverless.yml

On July 30, 2021, there will be the first phase of the end of support for AWS Lambda Ruby 2.5 runtime (https://docs.aws.amazon.com/lambda/latest/dg/runtime-support-policy.html).
Within the `examples` there are only two projects, which have `ruby2.5` runtime:
- [aws-ruby-line-bot](https://github.com/serverless/examples/tree/master/aws-ruby-line-bot)
-  [aws-ruby-simple-http-endpoint](https://github.com/serverless/examples/tree/master/aws-ruby-simple-http-endpoint)
The solution is pretty easy, simple I've updated the runtime from `2.5` to `2.7` for those two projects.
It is always good to have up-to-date examples of projects.

chore: Update `ruby` runtime from 2.5 to 2.7

---

aws-python-flask-api/requirements.txt
aws-python-flask-dynamodb-api/requirements.txt

Update `Flask` and explicitly lock `Werkzeug` version as recently released `Werkzeug` in `v2` is not compatible with Lambda runtime.

fix: Update dependencies for Python Flask for Lambda compatibility

---

openwhisk-python-simple/serverless.yml

Deploying with previous code results in this error: 
Failed to deploy function (openwhisk-python-simple-dev-greeting) due to error: PUT https://eu-gb.functions.cloud.ibm.com/api/v1/namespaces/_/actions/openwhisk-python-simple-dev-greeting?overwrite=true Returned HTTP 400 (Bad Request) --> "The 'python' runtime is no longer supported. You may read and delete but not update or invoke this action."

fix: Update `runtime` for `openwhisk-python-simple` example.

---

openwhisk-python-scheduled-cron/serverless.yml
openwhisk-python-simple-http-endpoint/serverless.yml

Related to: https://github.com/serverless/examples/pull/627

fix: Update `runtime` for `openwhisk-python-*` examples

---

aws-golang-auth-examples/Makefile
aws-golang-dynamo-stream-to-elasticsearch/Makefile
aws-golang-googlemap/Makefile
aws-golang-http-get-post/Makefile
aws-golang-s3-file-replicator/Makefile
aws-golang-simple-http-endpoint/Makefile
aws-golang-stream-kinesis-to-elasticsearch/Makefile

Related to: https://github.com/serverless/serverless/pull/9646

fix: Ensure to use `amd64` arch for `golang` examples

---

aws-node-twilio-send-text-message/README.md
aws-node-twilio-send-text-message/package.json
aws-node-twilio-send-text-message/serverless.yml

Fix for the lodash dependency error with the Twilio example.
Several problems, there was an error occurring with the previous Twilio version.
* Twilio v2.11.1 was causing an import module error.  (Upgraded to 3.65.0)
* Twilio v3.65.0 was causing the error in Issue #622 
Fixes:
* Updated Mocha to v9.0.2 (fixes critical errors)
* Removed node_modules exclusion line in `serverless.yml` and replaced with extra `npm i --only=prod` step in the README
All unit tests pass, Twilio successfully sends SMS message.

fix: `lodash` dependency for `twilio` example

---

aws-node-sqs-worker/README.md
aws-python-sqs-worker/README.md

I went over the README to see if there was anything that could be improved.
This PR is very light, but I mostly tried to make documentation links more obvious (since this template includes Lift, which is pretty new to both new _and_ experienced Framework users).
Slight changes also to remove a few words: for non-native English speakers, simpler sentences are always a bit easier to read.
That's a suggestion anyway, we can discuss this in the meeting later today!

docs: Improve the docs of the `aws-*-sqs-worker` examples

---

aws-golang-http-get-post/Makefile
aws-golang-http-get-post/getFolder/go.mod
aws-golang-http-get-post/getFolder/go.sum
aws-golang-http-get-post/postFolder/go.mod
aws-golang-http-get-post/postFolder/go.sum

I tried to follow the go + aws example (see issue #647) and hit a few roadblocks. This PR allows to compile the example again, although I don't think the package structure is very "go-like".
Signed-off-by: Hanno Kolvenbach <hannokolvenbach@gmx.de>

Use modules in go example instead of dep

---

aws-java-simple-http-endpoint/README.md
aws-java-simple-http-endpoint/serverless.yml
aws-node-simple-http-endpoint/README.md
aws-node-simple-http-endpoint/serverless.yml
aws-python-simple-http-endpoint/README.md
aws-python-simple-http-endpoint/serverless.yml
aws-ruby-simple-http-endpoint/README.md
aws-ruby-simple-http-endpoint/serverless.yml
openwhisk-python-simple-http-endpoint/README.md
openwhisk-python-simple-http-endpoint/serverless.yml
openwhisk-swift-simple-http-endpoint/README.md
openwhisk-swift-simple-http-endpoint/serverless.yml

This should ensure that all examples work as intended.
/ping is a default path and provides a healthcheck, for that reason it shouldn't be used.
Related to #667

fix: Chang `/ping` path to `/time` in several examples

---

README.md
aws-node-http-api-typescript/README.md
aws-node-http-api-typescript/handler.ts
aws-node-http-api-typescript/package.json
aws-node-http-api-typescript/serverless.yml

I wanted try out Serverless v3. When using the **aws-node-http-api-typescript** template (selected via the dashboard) and deploying right after creating the project, I faced an error:
This PR:
* Updates the example to work with v3 out of the box
* Uses Node.js 14.x (previously 12.x)
* Updates other packages (e.g. TypeScript, serverless-plugin-typescript)
* Removes the **serverless-offline** package as it was not in use
* Removes the `lambdaHashingVersion` property from serverless.yml as it is [deprecated](https://www.serverless.com/framework/docs/deprecations/).
I tested this with a fresh deployment and it works fine!

feat: Update `aws-node-http-api-typescript` to `v3` and Node 14

---

legacy/aws-csharp/Handler.cs
legacy/aws-csharp/aws-csharp.csproj
legacy/aws-csharp/build.cmd
legacy/aws-csharp/build.sh
legacy/aws-csharp/serverless.yml
legacy/aws-fsharp/aws-fsharp.fsproj
legacy/aws-fsharp/build.cmd
legacy/aws-fsharp/build.sh
legacy/aws-fsharp/serverless.yml

Updates the C# and F# AWS Lambda legacy templates to use the .NET 6 managed Lambda runtime.

feat: Update `.net` examples to .NET 6

---

aws-node-typescript/.gitignore
aws-node-typescript/README.md
aws-node-typescript/handler.ts
aws-node-typescript/package.json
aws-node-typescript/serverless.yml
examples.json

This follows the discussion in https://github.com/serverless/examples/pull/681#issuecomment-1052007939
This is a basic TypeScript example based on the basic Node (JS) example. It uses the `esbuild` plugin as discussed in https://github.com/serverless/serverless/issues/10700

Create a basic TypeScript example

---

aws-node-graphql-api-with-dynamodb/README.md
aws-node-graphql-api-with-dynamodb/handler.js

graphql function params are passed incorrectly in example
https://stackoverflow.com/questions/70567470/error-expected-undefined-to-be-a-graphql-schema-on-hello-world

fix: GraphQL query endpoint errors

---

aws-python-telegram-bot/handler.py
aws-python-telegram-bot/package.json
aws-python-telegram-bot/requirements.txt
aws-python-telegram-bot/serverless.yml

Current example `aws-python-telegram-bot` does not work with old version of serverless-python-requirements
so upgrade to latest version .
When changed from API gateway v1 to v2 httpApi, some fields in the  are changed.

feat: Update `aws-python-telegram-bot` to v3 and using httpApi

---

examples.json

I don't what I did in #700 but I think I submitted my PR without having actually finished it 😣 (duplicated example + did not change the "name" field)
Anyway, now that the examples are updating again on https://www.serverless.com/examples I realized there was a problem.

fix: Laravel examples

---

aws-golang-http-get-post/serverless.yml

Golang http-get-post sample contained invalid servlerless.yml configuration which caused lambda function to fail due to missing handler binary.

fix golang http-get-post sample

---

aws-python-rest-api/handler.py
aws-python-rest-api/serverless.yml

Update python and framework version for `aws-python-rest-api` example

---

aws-python-http-api/serverless.yml

feat: Update python to 3.9 in `aws-python-http-api` example

---

community-examples.json

Added the following community example:
[AWS SQS + TypeScript + ElasticMQ](https://github.com/nanlabs/devops-reference/tree/main/examples/serverless-sqs-node-typescript-offline-with-elasticmq/) - Serverless Framework example to run AWS SQS service locally environment using [Serverless Offline](https://www.serverless.com/plugins/serverless-offline) and [ElasticMQ](https://github.com/softwaremill/elasticmq).
This example comes from [NaNLABS' DevOps Reference](https://github.com/nanlabs/devops-reference).

Add example to community-examples.json

---

community-examples.json

Add [AWS SQS + Python + Localstack](https://github.com/nanlabs/devops-reference/tree/main/examples/serverless-sqs-python) - Serverless Framework example to run AWS SQS service locally environment using [Serverless Offline](https://www.serverless.com/plugins/serverless-offline) and [Localstack](https://github.com/localstack).
This example comes from [NaNLABS' DevOps Reference](https://github.com/nanlabs/devops-reference).

feat: add sqs offline with python and localstack example

---

aws-node-rest-api-typescript/package.json

stop npm install from failing for 
`serverless --template-url=https://github.com/serverless/examples/tree/v3/aws-node-rest-api-typescript`
this resolves version conflicts between version of TSLint that is required by the root project and the version required by the "tslint-config-airbnb" package.
this issue may be present on other examples too so pls check and resolve as required.

revert update for tslint

---

aws-node-single-page-app-via-cloudfront/serverless.yml

Related to: https://aws.amazon.com/blogs/aws/amazon-s3-block-public-access-another-layer-of-protection-for-your-accounts-and-buckets/
Fixes:-
- error `Bucket cannot have ACLs set with ObjectOwnership's BucketOwnerEnforced setting`
- error `An error occurred: WebAppS3BucketPolicy - API: s3:PutBucketPolicy Access Denied.`
- error `Bucket name should not contain uppercase character`

fix: aws-node-single-page-app-via-cloudfront config
