serverless/examples

aws-node-serve-dynamic-html/README.md
aws-node-serve-dynamic-html/handler.js
aws-node-serve-dynamic-html/serverless.yml
aws-node-single-page-app-via-cloudfront/README.md

Bare bones API gateway dynamic HTML response

add simple dynamic html example

---

README.md
aws-node-env-variables/package.json
aws-node-scheduled-cron/package.json
aws-node-serve-dynamic-html-via-http-endpoint/package.json
aws-node-simple-http-endpoint/package.json
aws-node-text-analysis-via-sns-post-processing/package.json
aws-python-simple-http-endpoint/package.json
community-examples.json
generate-readme.js
package.json

`npm run docs` will sync all examples to the readme.

Add meta data to examples and doc gen to keep readme up to date

---

aws-python-scheduled-cron/README.md
aws-python-scheduled-cron/handler.py
aws-python-scheduled-cron/package.json
aws-python-scheduled-cron/serverless.yml

add schedules cron example

---

community-examples.json

Adding serverless-python-sample with dependencies

add serverless-python-sample

---

aws-node-twilio-send-text-message/.gitignore
aws-node-twilio-send-text-message/.npmignore
aws-node-twilio-send-text-message/README.md
aws-node-twilio-send-text-message/event.json
aws-node-twilio-send-text-message/frontend/app.css
aws-node-twilio-send-text-message/frontend/index.html
aws-node-twilio-send-text-message/handler.js
aws-node-twilio-send-text-message/package.json
aws-node-twilio-send-text-message/serverless.yml

add twilio example

---

README.md
openwhisk-node-simple/README.md
openwhisk-node-simple/delay.js
openwhisk-node-simple/hello_world.js
openwhisk-node-simple/left_pad.js
openwhisk-node-simple/package.json
openwhisk-node-simple/serverless.yml

Add OpenWhisk boilerplate

---

aws-node-github-webhook-listener/.gitignore
aws-node-github-webhook-listener/README.md
aws-node-github-webhook-listener/handler.js
aws-node-github-webhook-listener/package.json
aws-node-github-webhook-listener/serverless.yml

add github web hook listener lambda ⊂◉‿◉つ

---

aws-node-rest-api-with-dynamodb/todos/create.js
aws-node-rest-api-with-dynamodb/todos/delete.js
aws-node-rest-api-with-dynamodb/todos/get.js
aws-node-rest-api-with-dynamodb/todos/list.js
aws-node-rest-api-with-dynamodb/todos/update.js

Fixes a typo in a comment across a couple of files.

Fix typo resonse -> response

---

README.md
aws-java-simple-http-endpoint/.gitignore
aws-java-simple-http-endpoint/README.md
aws-java-simple-http-endpoint/build.gradle
aws-java-simple-http-endpoint/gradle/wrapper/gradle-wrapper.properties
aws-java-simple-http-endpoint/gradlew
aws-java-simple-http-endpoint/gradlew.bat
aws-java-simple-http-endpoint/pom.xml
aws-java-simple-http-endpoint/serverless.yml
aws-java-simple-http-endpoint/src/main/java/com/serverless/ApiGatewayResponse.java
aws-java-simple-http-endpoint/src/main/java/com/serverless/Handler.java
aws-java-simple-http-endpoint/src/main/java/com/serverless/Response.java
aws-java-simple-http-endpoint/src/main/resources/log4j.properties

Bbilger master

---

aws-node-single-page-app-via-cloudfront/serverless-single-page-app-plugin/index.js

Fix issue with es6 syntax preventing deployment of cloudfront SPA.

---

aws-node-recursive-function/README.md
aws-node-recursive-function/event.json
aws-node-recursive-function/handler.js
aws-node-recursive-function/serverless.yml

Add recursive invocation example and readme

add node recursive invocation example

---

aws-node-single-page-app-via-cloudfront/serverless-single-page-app-plugin/index.js

Jerwallace master

---

community-examples.json

This PR adds sc5 serverless boilerplate and Amazon Polly - blog to podcast service to community examples.

add sc5 serverless boilerplate and blog to podcast service to community examples

---

README.md
openwhisk-node-chaining-functions/README.md
openwhisk-node-chaining-functions/handler.js
openwhisk-node-chaining-functions/package.json
openwhisk-node-chaining-functions/serverless.yml
openwhisk-node-chaining-functions/utils.js
openwhisk-node-scheduled-cron/README.md
openwhisk-node-scheduled-cron/handler.js
openwhisk-node-scheduled-cron/package.json
openwhisk-node-scheduled-cron/serverless.yml
openwhisk-node-simple-http-endpoint/README.md
openwhisk-node-simple-http-endpoint/handler.js
openwhisk-node-simple-http-endpoint/package.json
openwhisk-node-simple-http-endpoint/serverless.yml
openwhisk-node-simple/README.md

Added HTTP events, schedule events and function chaining examples.
I've verified the `npm lint` command to ensure the style is correct.

Adding new OpenWhisk examples.

---

community-examples.json

Add Offset Trump site to examples

---

.eslintrc.json
aws-node-auth0-custom-authorizers-api/frontend/app.js
aws-node-env-variables-encrypted-in-a-file/handler.js
aws-node-env-variables/handler.js
aws-node-function-compiled-with-babel/handler.js
aws-node-iot-event/handler.js
aws-node-rest-api-with-dynamodb/todos/create.js
aws-node-rest-api-with-dynamodb/todos/delete.js
aws-node-rest-api-with-dynamodb/todos/get.js
aws-node-rest-api-with-dynamodb/todos/list.js
aws-node-rest-api-with-dynamodb/todos/update.js
aws-node-scheduled-cron/handler.js
aws-node-text-analysis-via-sns-post-processing/addNote.js
aws-node-text-analysis-via-sns-post-processing/analyzeNote.js
openwhisk-node-scheduled-cron/handler.js

eslint: disable no-console

---

README.md
aws-python-rest-api-with-dynamodb/README.md
aws-python-rest-api-with-dynamodb/package.json
aws-python-rest-api-with-dynamodb/serverless.yml
aws-python-rest-api-with-dynamodb/todos/create.py
aws-python-rest-api-with-dynamodb/todos/decimalencoder.py
aws-python-rest-api-with-dynamodb/todos/delete.py
aws-python-rest-api-with-dynamodb/todos/get.py
aws-python-rest-api-with-dynamodb/todos/list.py
aws-python-rest-api-with-dynamodb/todos/update.py

Adds a python REST example using DynamoDB.
fixes #13

add aws-python-rest-api-with-dynamodb

---

.gitignore

gitignore: add vim swap files

---

aws-node-rest-api-with-dynamodb/todos/delete.js
aws-node-rest-api-with-dynamodb/todos/get.js

These were likely copy-pasted from create.js and list.js respectively.

fix comments

---

aws-node-rest-api-with-dynamodb/README.md

- remove sentence about nonexistent todos/index.js
- remove extra word
- add example output for update

aws-node-rest-api-with-dynamodb: fix README

---

aws-node-auth0-custom-authorizers-api/frontend/app.js

Set a valid cache mode. See:
https://fetch.spec.whatwg.org/#concept-request-cache-mode

fix cache mode

---

community-examples.json

Include serverless-html-pdf example.

Add new example

---

README.md

regenerate README after example rename

---

.travis.yml
check-if-readme-is-up-to-date.sh

travis: check if docs have been generated

---

README.md
check-if-readme-is-up-to-date.sh

Fix readme check

---

README.md
community-examples.json

Add adoptable-pet-bot to community examples

---

aws-node-rest-api-with-dynamodb-and-offline/README.md
aws-node-rest-api-with-dynamodb-and-offline/todos/create.js
aws-node-rest-api-with-dynamodb/README.md
aws-node-rest-api-with-dynamodb/todos/create.js

dynamodb: return item on create

---

aws-node-fetch-file-and-store-in-s3/handler.js

aws-node-fetch-file-and-store-in-s3: check response first

---

aws-node-fetch-file-and-store-in-s3/handler.js

aws-node-fetch-file-and-store-in-s3: improve error message

---

aws-node-fetch-file-and-store-in-s3/handler.js

aws-node-fetch-file-and-store-in-s3: use url from response

---

README.md
aws-node-rekognition-analysis-s3-image/.gitignore
aws-node-rekognition-analysis-s3-image/README.md
aws-node-rekognition-analysis-s3-image/handler.js
aws-node-rekognition-analysis-s3-image/lib/imageAnalyser.js
aws-node-rekognition-analysis-s3-image/package.json
aws-node-rekognition-analysis-s3-image/post.json
aws-node-rekognition-analysis-s3-image/serverless.yml

Serverless Node.js example using Amazon Rekognition

---

aws-node-rest-api-with-dynamodb-and-offline/README.md

Updates procedure to be able to successfully load locally.  This fixes issue https://github.com/serverless/examples/issues/146

update docs setup procedure

---

README.md
community-examples.json
package.json

Fixing merge conflicts for https://github.com/serverless/examples/pull/133
Thanks @cristim for the PR!

Add golang example

---

README.md
community-examples.json

This PR will add video preview and analysis service to the community examples.

Add video preview and analysis service to community examples

---

community-examples.json

Add Serverless ES6/7 CRUD API example

---

README.md
community-examples.json

Hoping this will help people to get started building a GraphQL API using the Serverless Framework. This also shows how to use [graphql-tools](https://github.com/apollographql/graphql-tools) and [gql-merge](https://github.com/liamcurry/gql/tree/master/packages/gql-merge) to merge and generate a schema for large projects.

Added my GraphQL example project

---

azure-node-simple-http-endpoint/README.md
azure-node-simple-http-endpoint/handler.js
azure-node-simple-http-endpoint/package.json
azure-node-simple-http-endpoint/serverless.yml
package-lock.json

Updated the documentation and configuration to follow the new login
method - there's no need to configure the environment variables; updated
the example to be a little less cluttered; updated the sample commands
to pass data to the invoke command.

Update the Azure example to match recent updates.

---

README.md
generate-readme.js
openwhisk-swift-precompiled-binaries/Package.swift
openwhisk-swift-precompiled-binaries/README.md
openwhisk-swift-precompiled-binaries/Sources/hello/main.swift
openwhisk-swift-precompiled-binaries/Sources/welcome/main.swift
openwhisk-swift-precompiled-binaries/package.json
openwhisk-swift-precompiled-binaries/serverless.yml

New example showing how to speed up Swift actions on OpenWhisks using pre-compiled binaries. 
Also uses external packages to pull in more libraries.

Add new example demonstrating pre-compiled Swift actions

---

aws-node-github-webhook-listener/handler.js

#172 Fixing the example to match the fix I got from @DavidWells in my repo https://github.com/netlify/netlify-cms-docs-webhook/pull/1/files

removes JSON manipulation in calculated signing

---

aws-multiple-runtime/api/handler.js

aws-multiple-runtime: fix linting issues

---

README.md
community-examples.json

Add slack-signup-serverless sample app.

---

aws-node-auth0-custom-authorizers-api/README.md

No such file as `frontend/app.j`. Changed to`frontend/app.js`.

Minor file extension fix in a comment.

---

README.md
aws-python-rest-api-with-pynamodb/.gitignore
aws-python-rest-api-with-pynamodb/README.md
aws-python-rest-api-with-pynamodb/package-lock.json
aws-python-rest-api-with-pynamodb/package.json
aws-python-rest-api-with-pynamodb/requirements.txt
aws-python-rest-api-with-pynamodb/serverless.yml
aws-python-rest-api-with-pynamodb/todos/create.py
aws-python-rest-api-with-pynamodb/todos/delete.py
aws-python-rest-api-with-pynamodb/todos/get.py
aws-python-rest-api-with-pynamodb/todos/list.py
aws-python-rest-api-with-pynamodb/todos/todo_model.py
aws-python-rest-api-with-pynamodb/todos/update.py

I know that likely that this is too complex compared to the other examples. I am wondering if this example interests you. If not I will break it out into another repo. I have one remaining clear todo. Just wanted to check in

Example of rest api with Pynamodb

---

openwhisk-swift-precompiled-binaries/README.md
openwhisk-swift-precompiled-binaries/package.json

Update Swift Docker image to current version

---

community-examples.json

*Purpose:* Adds a simple template to highlight the gitlab ci and demo a basic nodejs config
*Lint:* Success!
*Description:* Demo a simple configuration with free tier resources on gitlab.com. Includes install instructions and modification details. The actual config creates a simple `test  >> deploy` pipeline for the staging and master branches.

Add Gitlab CI template

---

community-examples.json

add bablebot community-examples.json

---

kubeless-python-schedule/handler.py
kubeless-python-schedule/package.json
kubeless-python-simple/handler.py
kubeless-python-simple/package.json

The function format has changed. This PR adapts existing functions to the new format.

Adapt examples to kubeless 0.5

---

openwhisk-go-simple/README.md
openwhisk-go-simple/package.json
openwhisk-node-and-docker-chaining-functions/README.md
openwhisk-node-and-docker-chaining-functions/package.json
openwhisk-node-chaining-functions/README.md
openwhisk-node-chaining-functions/package.json
openwhisk-node-scheduled-cron/README.md
openwhisk-node-scheduled-cron/package.json
openwhisk-node-simple-http-endpoint/README.md
openwhisk-node-simple-http-endpoint/package.json
openwhisk-node-simple/README.md
openwhisk-node-simple/package.json
openwhisk-php-simple/README.md
openwhisk-php-simple/package.json
openwhisk-python-scheduled-cron/README.md
openwhisk-python-scheduled-cron/package.json
openwhisk-python-simple-http-endpoint/README.md
openwhisk-python-simple-http-endpoint/package.json
openwhisk-python-simple/README.md
openwhisk-python-simple/package.json
openwhisk-swift-precompiled-binaries/README.md
openwhisk-swift-precompiled-binaries/package.json
openwhisk-swift-scheduled-cron/README.md
openwhisk-swift-scheduled-cron/package.json
openwhisk-swift-simple-http-endpoint/README.md
openwhisk-swift-simple-http-endpoint/package.json
openwhisk-swift-simple/README.md
openwhisk-swift-simple/package.json

See https://github.com/serverless/serverless/pull/5015

Updating OpenWhisk provider plugin instructions

---

README.md

Update meetups link

---

README.md
community-examples.json

Community Example (Java/Spring/Cloud/Function/AWS/Serverless)

---

README.md
aws-python-auth0-custom-authorizers-api/.gitignore
aws-python-auth0-custom-authorizers-api/Makefile
aws-python-auth0-custom-authorizers-api/README.md
aws-python-auth0-custom-authorizers-api/frontend/app.css
aws-python-auth0-custom-authorizers-api/frontend/app.js
aws-python-auth0-custom-authorizers-api/frontend/index.html
aws-python-auth0-custom-authorizers-api/lambda_handlers.py
aws-python-auth0-custom-authorizers-api/package.json
aws-python-auth0-custom-authorizers-api/public_key-example
aws-python-auth0-custom-authorizers-api/requirements.txt
aws-python-auth0-custom-authorizers-api/secrets.example.json
aws-python-auth0-custom-authorizers-api/serverless.yml

Added Python AWS Lambda Authorizer

---

README.md
aws-golang-simple-http-endpoint/Gopkg.toml
aws-golang-simple-http-endpoint/Makefile
aws-golang-simple-http-endpoint/hello/main.go
aws-golang-simple-http-endpoint/package.json
aws-golang-simple-http-endpoint/serverless.yml
aws-golang-simple-http-endpoint/world/main.go
generate-readme.js
package-lock.json

Adding a basic golang http endpoint handler for AWS

AWS simple golang http endpoint example

---

aws-node-graphql-api-with-dynamodb/handler.js

I checked out your project and was getting this (in eu-central-1/Frankfurt):
Syntax error in module 'handler': SyntaxError
);
^
SyntaxError: Unexpected token )
at createScript (vm.js:56:10)
at Object.runInThisContext (vm.js:97:10)
at Module._compile (module.js:542:28)
at Object.Module._extensions..js (module.js:579:10)
at Module.load (module.js:487:32)
at tryModuleLoad (module.js:446:12)
at Function.Module._load (module.js:438:3)
at Module.require (module.js:497:17)
at require (internal/module.js:20:19)

removed comma

---

package-lock.json
package.json

Handle the github warning for bad dependency in `package-lock.json`.

updating package deps

---

aws-python-auth0-custom-authorizers-api/requirements.txt

Updating the python vulnerability in requirements library

updating vuln for crypto in python example

---

aws-node-serve-dynamic-html-via-http-endpoint/README.md

Fix typos in README.md

---

aws-node-rekognition-analysis-s3-image/README.md

Minor typo fix

---

README.md
azure-node-telegram-bot/README.md
azure-node-telegram-bot/handler.js
azure-node-telegram-bot/package.json
azure-node-telegram-bot/serverless.yml

added nodejs telegram bot example with azure function. 🤖

Added azure-node-telegram-bot example 

---

README.md
community-examples.json

Added entry to community examples

---

aws-node-scheduled-cron/README.md

Update README.md to fix out-of-order words.

---

aws-python-auth0-custom-authorizers-api/lambda_handlers.py

Fixes upstream #305 by using `Exception('Unauthorized')` instead of
returning a 401 response.
See the [AWS example](https://github.com/awslabs/aws-apigateway-lambda-authorizer-blueprints/blob/50626da2512a16a8850db792939ada5b47571b4f/blueprints/python/api-gateway-authorizer-python.py#L31).

Fail using Exception(..) not 401

---

aws-dotnet-rest-api-with-dynamodb/.gitignore
aws-dotnet-rest-api-with-dynamodb/TodoLambda.sln
aws-dotnet-rest-api-with-dynamodb/src/TodoLambda.Domain/Class1.cs
aws-dotnet-rest-api-with-dynamodb/src/TodoLambda.Domain/Entity/Item.cs
aws-dotnet-rest-api-with-dynamodb/src/TodoLambda.Domain/Handlers/CreateItemHandler.cs
aws-dotnet-rest-api-with-dynamodb/src/TodoLambda.Domain/Handlers/GetItemHandler.cs
aws-dotnet-rest-api-with-dynamodb/src/TodoLambda.Domain/Handlers/UpdateItemHandler.cs
aws-dotnet-rest-api-with-dynamodb/src/TodoLambda.Domain/Infrastructure/AWSClientFactory.cs
aws-dotnet-rest-api-with-dynamodb/src/TodoLambda.Domain/Infrastructure/AwsBasicConfiguration.cs
aws-dotnet-rest-api-with-dynamodb/src/TodoLambda.Domain/Infrastructure/DynamoDbConfiguration.cs
aws-dotnet-rest-api-with-dynamodb/src/TodoLambda.Domain/Requests/CreateItemRequest.cs
aws-dotnet-rest-api-with-dynamodb/src/TodoLambda.Domain/Requests/GetItemRequest.cs
aws-dotnet-rest-api-with-dynamodb/src/TodoLambda.Domain/Requests/UpdateItemRequest.cs
aws-dotnet-rest-api-with-dynamodb/src/TodoLambda.Domain/Responses/ItemResponse.cs
aws-dotnet-rest-api-with-dynamodb/src/TodoLambda.Domain/TodoLambda.Domain.csproj
aws-dotnet-rest-api-with-dynamodb/src/TodoLambda.Functions/Class1.cs
aws-dotnet-rest-api-with-dynamodb/src/TodoLambda.Functions/Program.cs
aws-dotnet-rest-api-with-dynamodb/src/TodoLambda.Functions/Startup.cs
aws-dotnet-rest-api-with-dynamodb/src/TodoLambda.Functions/TodoLambda.Functions.csproj
aws-dotnet-rest-api-with-dynamodb/src/TodoLambda.Functions/Todos/Create.cs
aws-dotnet-rest-api-with-dynamodb/src/TodoLambda.Functions/Todos/Get.cs
aws-dotnet-rest-api-with-dynamodb/src/TodoLambda.Functions/Todos/Update.cs

Init dotnet templates

---

aws-ffmpeg-layer/build.sh

pass -a to tar to decompress the xz tar file.

decompress xz file

---

aws-node-alexa-skill/serverless.yml
aws-node-auth0-cognito-custom-authorizers-api/serverless.yml
aws-node-env-variables-encrypted-in-a-file/serverless.yml
aws-node-env-variables/serverless.yml
aws-node-fetch-file-and-store-in-s3/serverless.yml
aws-node-function-compiled-with-babel/serverless.yml
aws-node-github-webhook-listener/README.md
aws-node-github-webhook-listener/serverless.yml
aws-node-iot-event/serverless.yml
aws-node-recursive-function/README.md
aws-node-recursive-function/serverless.yml
aws-node-rest-api-with-dynamodb-and-offline/serverless.yml
aws-node-scheduled-cron/serverless.yml
aws-node-scheduled-weather/serverless.yml
aws-node-serve-dynamic-html-via-http-endpoint/serverless.yml
aws-node-simple-http-endpoint/serverless.yml
aws-node-single-page-app-via-cloudfront/serverless.yml
aws-node-text-analysis-via-sns-post-processing/serverless.yml
aws-node-twilio-send-text-message/serverless.yml
aws-node-upload-to-s3-and-postprocess/serverless.yml

- runtime nodejs4.3 is no longer available on aws

update runtime nodejs4.3 to nodejs.8.10

---

README.md
community-examples.json

updated docs

---

aws-golang-http-get-post/Makefile
aws-golang-http-get-post/README.md
aws-golang-http-get-post/getFolder/getQueryExample.go
aws-golang-http-get-post/serverless.yml

Added another example for query param in get http in my old example
Please review, thanks a lot!

Added query param example in http get

---

aws-python-scheduled-cron/README.md

fix grammar

---

aws-ffmpeg-layer/README.md

Runs build script to download ffmpeg

---

README.md
aws-node-shared-gateway/README.md
aws-node-shared-gateway/ci-decomission.sh
aws-node-shared-gateway/ci-deploy.sh
aws-node-shared-gateway/gateway/.gitignore
aws-node-shared-gateway/gateway/serverless.yml
aws-node-shared-gateway/package.json
aws-node-shared-gateway/products/.gitignore
aws-node-shared-gateway/products/handler.js
aws-node-shared-gateway/products/serverless.yml
aws-node-shared-gateway/transactions/.gitignore
aws-node-shared-gateway/transactions/handler.js
aws-node-shared-gateway/transactions/serverless.yml
aws-node-shared-gateway/users/.gitignore
aws-node-shared-gateway/users/handler.js
aws-node-shared-gateway/users/serverless.yml

I am raising this pull request to donate a sample implementation of how a shared AWS API Gateway can be re-used between multiple lambda projects.

-Created a sample reference for shared API gateway for AWS and Node.

---

aws-node-github-check/README.md

typo fix in readme

---

aws-python-rest-api-with-dynamodb/todos/create.py

Set timezone for one source of truth later.

---

README.md
aws-ruby-line-bot/.gitignore
aws-ruby-line-bot/Gemfile
aws-ruby-line-bot/Gemfile.lock
aws-ruby-line-bot/README.md
aws-ruby-line-bot/handler.rb
aws-ruby-line-bot/package.json
aws-ruby-line-bot/serverless.yml

Use ruby to create a line echo bot on AWS

---

aws-python-line-echo-bot/README.md
aws-ruby-line-bot/README.md

- I found typos in some examples.
- I tried to fix it.

Fix typos in some examples

---

aws-golang-googlemap/README.md

add missing readme

---

azure-node-telegram-bot/README.md

typoe in README file

---

aws-python-rest-api-with-dynamodb/todos/create.py

fixes #480

---

aws-ffmpeg-layer/build.sh
aws-ffmpeg-layer/serverless.yml

- Fixed tar command 
- Bump'd the aws version 
Works perfectly fine now.

Fixing FFmpeg example.

---

google-node-simple-http-endpoint/README.md
google-node-simple-http-endpoint/package.json
google-node-simple-http-endpoint/serverless.yml

sync with latest GCP 

---

README.md

I added an explanation because it's hard to distinguish.

Add azure node explanation

---

README.md
aws-node-typescript-kinesis/.gitignore
aws-node-typescript-kinesis/README.md
aws-node-typescript-kinesis/handler.ts
aws-node-typescript-kinesis/kinesis/consumer.ts
aws-node-typescript-kinesis/kinesis/producer.ts
aws-node-typescript-kinesis/package-lock.json
aws-node-typescript-kinesis/package.json
aws-node-typescript-kinesis/serverless.yml
aws-node-typescript-kinesis/tsconfig.json
aws-node-typescript-kinesis/tslint.json
aws-node-typescript-kinesis/webpack.config.js

Adapted from SQS Standard example.
Dependencies updated.
Linting rules for my directory pass (using eslint aws-node-typescript-kinesis).
Doc updates generated.

Added and example of AWS Kinesis usage with node.js and Typescript

---

aws-node-rest-api-with-dynamodb-and-offline/serverless.yml

add dev stage to stages whitelist for aws-node-rest-api-with-dynamodb-and-offline

---

aws-ruby-line-bot/package.json
aws-ruby-line-bot/serverless.yml
aws-ruby-simple-http-endpoint/package.json
aws-ruby-simple-http-endpoint/serverless.yml

Just some quick bumps since we've been on version 2 for a while. 
Should make it easier for new people

Update Ruby frameworkVersion to 2

---

aws-node-scheduled-cron/README.md
aws-node-scheduled-cron/serverless.template.yml
aws-node-scheduled-cron/serverless.yml

Changes contain:
- Refresh template for the latest framework version, ensuring that there are no deprecations logged 
- Add `serverless.template.yml`
- Refresh the description

Refresh `aws-node-scheduled-cron` example

---

README.md
aws-python-sqs-worker/.gitignore
aws-python-sqs-worker/README.md
aws-python-sqs-worker/handler.py
aws-python-sqs-worker/package.json
aws-python-sqs-worker/serverless.template.yml
aws-python-sqs-worker/serverless.yml

Introduces new `aws-python-sqs-worker` example

feat: Add `aws-python-sqs-worker` example

---

README.md
aws-node-express-dynamodb-api/.gitignore
aws-node-express-dynamodb-api/README.md
aws-node-express-dynamodb-api/package.json
aws-node-express-dynamodb-api/serverless.template.yml
aws-node-express-dynamodb-api/serverless.yml
aws-node-express-dynamodb-api/src/app.js
aws-node-express-dynamodb-api/src/index.js

Introduces a `aws-node-express-dynamodb-api` template

feat: Add `aws-node-express-dynamodb-api`

---

README.md
aws-node-express-api/.gitignore
aws-node-express-api/README.md
aws-node-express-api/package.json
aws-node-express-api/serverless.template.yml
aws-node-express-api/serverless.yml
aws-node-express-api/src/app.js
aws-node-express-api/src/index.js

Introduce `aws-node-express-api` template

feat: Add `aws-node-express-api` template

---

aws-node-express-api/README.md
aws-node-rest-api/README.md
aws-node-rest-api/handler.js
aws-node-rest-api/serverless.yml

Refresh the `aws-node-rest-api` template

feat: Refresh `aws-node-rest-api` template

---

aws-node-express-api/serverless.yml
aws-node-express-dynamodb-api/serverless.yml
aws-node-rest-api/README.md
aws-node-rest-api/serverless.yml
aws-node-scheduled-cron/serverless.yml
aws-node-sqs-worker/serverless.yml
aws-python-flask-api/serverless.yml
aws-python-flask-dynamodb-api/serverless.yml
aws-python-rest-api/README.md
aws-python-rest-api/serverless.yml
aws-python-scheduled-cron/serverless.yml
aws-python-sqs-worker/serverless.yml

Changes:
- Cleanup settings in `serverless.yml` for templates
- Add more extensive init instructions to templates

feat: Cleanup configuration for templates

---

aws-node/.gitignore
aws-node/README.md
aws-node/handler.js
aws-node/serverless.yml
aws-python/.gitignore
aws-python/README.md
aws-python/handler.py
aws-python/serverless.yml

Part of: https://github.com/serverless/serverless/issues/9367

Add simple `aws-python` and `aws-node` examples

---

aws-node-s3-file-replicator/package-lock.json
aws-node-s3-file-replicator/package.json
aws-node-s3-file-replicator/serverless.yml

This PR aims at reducing required code base to implement and deploy `aws-node-s3-file-replicator` exemple using Lift plugin.
The plugin leverages `storage` constructs for both input and output buckets. It deploys required iamStatements to Lambda role policy to interact with those buckets.

feat: Update `aws-node-s3-file-replicator` with Lift construct

---

aws-ffmpeg-layer/serverless.yml
aws-golang-dynamo-stream-to-elasticsearch/serverless.yml
aws-golang-googlemap/serverless.yml
aws-golang-http-get-post/serverless.yml
aws-golang-rest-api-with-dynamodb/serverless.yml
aws-golang-s3-file-replicator/serverless.yml
aws-node-dynamodb-backup/serverless.yml
aws-node-fetch-file-and-store-in-s3/serverless.yml
aws-node-graphql-and-rds/serverless.yml
aws-node-graphql-api-with-dynamodb/serverless.yml
aws-node-recursive-function/serverless.yml
aws-node-rekognition-analysis-s3-image/serverless.yml
aws-node-rest-api-with-dynamodb-and-offline/serverless.yml
aws-node-rest-api-with-dynamodb/serverless.yml
aws-node-ses-receive-email-body/serverless.yml
aws-node-signed-uploads/serverless.yml
aws-node-simple-transcribe-s3/serverless.yml
aws-node-stripe-integration/serverless.yml
aws-node-text-analysis-via-sns-post-processing/serverless.yml
aws-node-typescript-kinesis/serverless.yml
aws-node-typescript-rest-api-with-dynamodb/serverless.yml
aws-node-typescript-sqs-standard/serverless.yml
aws-python-pynamodb-s3-sigurl/serverless.yml
aws-python-rest-api-with-dynamodb/serverless.yml
aws-python-rest-api-with-pymongo/serverless.yml
aws-python-rest-api-with-pynamodb/serverless.yml

Ensure to use modern syntax for IAM-related properties

refactor: Ensure use of modern `iam.role` syntax

---

aws-node-express-api/serverless.yml
aws-node-express-dynamodb-api/serverless.yml
aws-node-http-api/serverless.yml
aws-node-scheduled-cron/serverless.yml
aws-node-sqs-worker/serverless.yml
aws-node/serverless.yml
aws-python-flask-api/serverless.yml
aws-python-flask-dynamodb-api/serverless.yml
aws-python-http-api/serverless.yml
aws-python-scheduled-cron/serverless.yml
aws-python-sqs-worker/serverless.yml
aws-python/serverless.yml

feat: Ensure major examples are compatible with v3

---

community-examples.json

Add idempotent serverless function examples

---

README.md

Add a new community example to Readme and fix  issue #665

Add a new community example to Readme and fix issue #665

---

README.md
google-ruby-simple-http-endpoint/Gemfile
google-ruby-simple-http-endpoint/README.md
google-ruby-simple-http-endpoint/app.rb
google-ruby-simple-http-endpoint/package.json
google-ruby-simple-http-endpoint/serverless.yml

An example of a Google Cloud Functions Ruby function. 
Note: I ran `npm docs`, but it appears to have made a few other unintended(?) changes - let me know if I should revert.

feat: Add `google-ruby-simple-http-endpoint`

---

aws-node-express-api/serverless.yml
aws-node-express-dynamodb-api/serverless.yml
aws-node-http-api/serverless.yml
aws-node-scheduled-cron/serverless.yml
aws-node-sqs-worker/serverless.yml
aws-node/serverless.yml
aws-python-flask-api/serverless.yml
aws-python-flask-dynamodb-api/serverless.yml
aws-python-http-api/serverless.yml
aws-python-scheduled-cron/serverless.yml
aws-python-sqs-worker/serverless.yml
aws-python/serverless.yml

feat: Adjust major templates to v3 Framework release

---

aws-python-flask-api/README.md
aws-python-flask-api/serverless.yml
aws-python-flask-dynamodb-api/README.md
aws-python-flask-dynamodb-api/serverless.yml

feat: Use `httpApi` in Flask Python examples

---

examples.json

I figured I never linked to Bref examples. That will at least provide usable PHP examples for people that filter with the PHP language on the website.

Add PHP examples

---

aws-node-serve-dynamic-html-via-http-endpoint/README.md

remove mistaken character

---

aws-node-http-api-typescript/handler.ts
aws-node-http-api-typescript/package-lock.json
aws-node-http-api-typescript/package.json

Hi @pgrzesik, some improvements to the already existing repo. 
- added proper types for lambda event handler (it's pointless to use any here).
- updated packages.

feat: Improve the HTTP API typescript example

---

aws-node-serve-dynamic-html-via-http-endpoint/README.md
aws-node-serve-dynamic-html-via-http-endpoint/handler.js
aws-node-serve-dynamic-html-via-http-endpoint/package.json
aws-node-serve-dynamic-html-via-http-endpoint/serverless.yml

Hi, @pgrzesik small improvements:
- added SLS framework v.3
- added packages
- improved documentation
- etc

[Feature] Improve AWS node serve dynamic html via http

---

legacy/aws-nodejs-typescript/package.json

Closes https://github.com/middyjs/middy/issues/907

aws-nodejs-typescript: update middy

---

aws-python-flask-dynamodb-api/package.json
aws-python-flask-dynamodb-api/serverless.yml

Update plugins, Python version, and use `{sls:stage}` syntax in `aws-python-flask-dynamodb-api` example

Update `aws-python-flask-dynamodb-api` example

---

aws-python-flask-api/package.json
aws-python-flask-api/serverless.yml

Updates plugins to the newest version & upgrades Python to 3.9

Update deps & Python version

---

aws-python-sqs-worker/package.json
aws-python-sqs-worker/serverless.yml

feat: Update python to 3.9 and plugin deps for `aws-python-sqs-worker`

---

community-examples.json

Added the following community examples:
- [AWS AppSync + TypeScript](./examples/serverless/serverless-appsync-nodejs/) - Serverless Framework example to deploy an AWS AppSync API using TypeScript. It also has a local development environment using [Serverless Offline](https://www.serverless.com/plugins/serverless-offline).
- [AWS AppSync + Python](./examples/serverless/serverless-appsync-python/) - Serverless Framework example to deploy an AWS AppSync API using Python. It also has a local development environment using [Serverless Offline](https://www.serverless.com/plugins/serverless-offline).
- [AWS Glue with Python Shell and PySpark Jobs](./examples/serverless/serverless-glue/) - Serverless Framework example to deploy an AWS Glue job using Python Shell and PySpark.
- [Complete AWS Glue …

Update community-examples.json with examples from NaNLABS

---

community-examples.json

Added the following community example:
- [Serverless Cognito Local](https://github.com/nanlabs/devops-reference/tree/main/examples/serverless-cognito-local) - Serverless Framework example to run a cognito triggered lambda locally using [Serverless Offline](https://www.serverless.com/plugins/serverless-offline).
Updated githubUrl for all nanlabs examples:

Aws cognito local lambdas

---

community-examples.json

added PostgreSQL with Sequelize community example project.
